=== joestr/OpenM2/old-installer-updater/openm2_R_03_03_01/inst/m2_R330_20120716/www/modules/masterd/install/xml/install.dtd
<?xml encoding="ISO-8859-1"?>
<!--
********
install:
********
install node:
    Contains the installation nodes.
-->
<!ELEMENT install (instpkg | instxml | instsql | import)+>

<!--
********
instpkg:
********
instpkg node (within install node):
    Perform installation of another package. This source file must  be a file
    which is also defined through this dtd.

    sourcefile:         The name of the sourcefile. A relative path to
                        the installation directory can be set
                        Use "/" as file separator. This will be replaced by
                        the appropriate fileseparator of the operating system
-->
<!ELEMENT instpkg EMPTY>
<!ATTLIST instpkg
    sourcefile          CDATA #REQUIRED
>

<!--
********
instxml:
********
instxml node (within install node):
    Perform installation of one or more xml files.

    sourcefile:         The name of the sourcefile. A relative path to
                        the installation directory can be set
                        Use * to select multiple files within
                        the source directory
                        Use "/" as file separator. This will be replaced by
                        the appropriate fileseparator of the operating system
    destpath:           The m2 path for the destination container
                        Please use "/" as separator (but note that "/" and "\"
                        will be recognized as separator!)
    destid:             The external key id for the destination container. Must
                        be used in conjunction with destiddomain.
    destiddomain:       The domain for the external key id defined in
                        destid.

Remark: For defining the target container you can use either destpath or
        both destid and destiddomain together.
-->
<!ELEMENT instxml EMPTY>
<!ATTLIST instxml
    sourcefile          CDATA #REQUIRED
    destpath            CDATA #IMPLIED
    destid              CDATA #IMPLIED
    destiddomain        CDATA #IMPLIED
>

<!--
********
instsql:
********
instsql node (within install node):
    Perform installation of one or more sql files.

    sourcefile:         The name of the sourcefile. A relative path to
                        the installation directory can be set.
                        Use * to select multiple files within
                        the source directory.
                        Use "/" as fileseparator. This will be replaced by
                        the appropriate fileseparator of the operating system.
                        Use #DBDIR# as placeholder for the directory
                        with the dbtype-specific sources in absolute paths.
                        For relative paths this is not necessary.
    dispmode:           The display mode.
                        dispno .... don't display sql statements
                        dispone ... display first line of sql statements
                        dispfull .. display full sql statements
-->
<!ELEMENT instsql EMPTY>
<!ATTLIST instsql
    sourcefile          CDATA #REQUIRED
    dispmode            (dispno|dispone|dispfull) #IMPLIED
>


<!-- deprecated elements, just for backwards compatibility -->

<!--
*******
import:
*******
import node (within install node):
    Perform installation of one or more xml files.

    sourcefile:         The name of the sourcefile. A relative path to
                        the installation directory can be set
                        Use * to select multiple files within
                        the source directory
                        Use "/" as fileseparator. This will be replaced by
                        the appropriate fileseparator of the operating system
    destinationpath:    The m2 path for the destination container
                        Please use "/" as separator (but note that "/" and "\"
                        will be recognized as separator!)

@deprecated This element should not be longer used. It will be dropped in a
            future release. Please use instxml instead.
-->
<!ELEMENT import EMPTY>
<!ATTLIST import
    sourcefile          CDATA #REQUIRED
    destinationpath     CDATA #REQUIRED
>

=== joestr/OpenM2/old-installer-updater/openm2_R_03_03_01/inst/m2_R330_20120716/www/modules/masterd/install/xml/install.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE install SYSTEM "install.dtd">
<!--
	multi-installer configuration file
	this file defines the steps for an installation
-->
<install>
	<!-- create common structures -->
	<instxml sourcefile="common/structures.xml" destiddomain="ibs_instobj" destid="di" />

	<!-- create the queryobject structures -->
	<instxml sourcefile="queryobjects/structures.xml" destiddomain="masterd_install" destid="Queries" />

	<!-- create the queryobjects -->
	<instxml sourcefile="queryobjects/reports/*.xml" destiddomain="masterd_instquery" destid="Berichte" />
	<instxml sourcefile="queryobjects/search/*.xml" destiddomain="masterd_instquery" destid="Suchmasken" />
	<instxml sourcefile="queryobjects/system/*.xml" destiddomain="masterd_instquery" destid="System" />
	<instxml sourcefile="queryobjects/misc/*.xml" destiddomain="masterd_instquery" destid="Sonstige" />

	<!-- create the connectors -->
	<!-- nothing to do -->

	<!-- create the importscrips -->
	<!-- nothing to do -->

	<!-- create the translators -->
	<!-- nothing to do -->

	<!-- create the workflowtemplates -->
	<!-- nothing to do -->

	<!-- create the formtemplates structures -->
	<!-- nothing to do -->

	<!-- create the formtemplates -->
	<!-- masterdata -->
	<instxml sourcefile="formtemplates/masterd/structures.xml"
		destiddomain="masterd_install" destid="Formularvorlagen" />

	<!-- stucture templates -->
	<!-- nothing to do -->

	<!-- create common object structures -->
	<instxml sourcefile="common/usergroups.xml"	destiddomain="ibs_instobj" destid="groups" />
	<instxml sourcefile="common/objects.xml" destiddomain="ibs_instobj"	destid="menuobjects" />
	<instxml sourcefile="common/menutabs.xml" destiddomain="ibs_instobj" destid="menutabs" />
</install>

=== joestr/OpenM2/old-installer-updater/openm2_R_03_03_01/wwwAddOn/modules/ibsbase/install/xml/install.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- $Id: install.xml,v 1.14 2011/10/18 14:53:08 rburgermann Exp $ -->
<!DOCTYPE install SYSTEM "install.dtd">
<!--
    multi-installer configuration file
    this file defines the steps for an installation
-->
<install>
    <!-- create common package structures -->
    <instxml sourcefile="common/structures.xml"
             destiddomain="ibs_instobj" destid="di"/>

    <!-- create the queryobject structures -->
    <instxml sourcefile="queryobjects/structures.xml"
             destiddomain="ibs_install" destid="Queries"/>
    <!-- create the queryobjects -->
    <instxml sourcefile="queryobjects/reports/*.xml"
             destiddomain="ibs_instquery" destid="Berichte"/>
    <instxml sourcefile="queryobjects/search/*.xml"
             destiddomain="ibs_instquery" destid="Suchmasken"/>
    <instxml sourcefile="queryobjects/system/*.xml"
             destiddomain="ibs_instquery" destid="System"/>
    <instxml sourcefile="queryobjects/misc/*.xml"
             destiddomain="ibs_instquery" destid="Sonstige"/>

    <!-- create the connectors -->
    <instxml sourcefile="connectors/structures.xml"
             destiddomain="ibs_install" destid="Konnektoren"/>

    <!-- create the importscrips -->
    <instxml sourcefile="importscripts/structures.xml"
             destiddomain="ibs_install" destid="Importskripts"/>

    <!-- create the translators -->
    <instxml sourcefile="translators/structures.xml"
             destiddomain="ibs_install" destid="Translatoren"/>

    <!-- create the workflowtemplates -->
    <instxml sourcefile="workflows/structures.xml"
             destiddomain="ibs_install" destid="Workflowvorlagen"/>


    <!-- create the formtemplates structures -->
<!--
    <instxml sourcefile="formtemplates/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
-->

    <!-- create the formtemplates -->
    <!-- value domain -->
    <instxml sourcefile="formtemplates/valuedomain/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
    <!-- database connector -->
    <instxml sourcefile="formtemplates/dbcon/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
    <!-- external database -->
    <instxml sourcefile="formtemplates/extdb/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
    <!-- webdav -->
    <instxml sourcefile="formtemplates/webdav/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
    <!-- reorg -->
    <instxml sourcefile="formtemplates/reorg/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
    <!-- includes -->
    <instxml sourcefile="formtemplates/include/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
    <!-- configuration -->
    <instxml sourcefile="formtemplates/config/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
    <!-- valuedomain -->
    <instxml sourcefile="formtemplates/valuedomain/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
    <!-- query -->
    <instxml sourcefile="formtemplates/query/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>

    <!-- export 
    <instxml sourcefile="formtemplates/export/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
             -->

    <!-- import
    <instxml sourcefile="formtemplates/import/structures.xml"
             destiddomain="ibs_install" destid="Formularvorlagen"/>
             -->

    <!-- stucture templates -->
    <instxml sourcefile="structures/structures.xml"
             destiddomain="ibs_install" destid="Strukturvorlagen"/>

    <!-- templates for standard users -->
    <instxml sourcefile="structures/workspaceTemplate_Administrator.xml"
             destiddomain="ibs_install" destid="Strukturvorlagen"/>
    <instxml sourcefile="structures/workspaceTemplate_SysAdmin.xml"
             destiddomain="ibs_install" destid="Strukturvorlagen"/>
    <instxml sourcefile="structures/workspaceTemplate_Debug.xml"
             destiddomain="ibs_install" destid="Strukturvorlagen"/>

    <!-- create common object structures -->
    <instxml sourcefile="common/usergroups.xml"
             destiddomain="ibs_instobj" destid="groups"/>
    <instxml sourcefile="common/objects.xml"
             destiddomain="ibs_instobj" destid="menuobjects"/>
    <instxml sourcefile="common/menutabs.xml"
             destiddomain="ibs_instobj" destid="menutabs"/>

    <!-- create the base workspace references -->
    <instsql sourcefile="../sql_ibsbase/#DBDIR#/install/createBaseWorkspaceRefs.sql" dispmode="dispone"/>
             
</install>
